[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm']

[phases.install]
cmds = [
  'cd backend',
  'npm ci --production'
]

[phases.build]
cmds = [
  'cd backend', 
  'npx prisma generate',
  'npm run build'
]

[start]
cmd = 'sh -c "cd backend && npx prisma migrate deploy && npm run start:prod"'
