[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm']

[phases.install]
cmds = [
  'cd backend',
  'npm install'
]

[phases.build]
cmds = [
  'cd backend', 
  'npx prisma generate',
  'npm run build'
]

[start]
cmd = 'cd backend && npm run start:prod'
