FROM node:18-alpine

WORKDIR /app

# Copiar tudo
COPY . .

# Instalar dependências
RUN npm install

# Gerar Prisma Client
RUN npx prisma generate

# Build
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
